version: '3'
services:
  db:
    image: postgres:13
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: student_reports
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  logstash:
    image: logstash:7.10.1
    platform: linux/amd64
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5100:5000"

  elasticsearch:
    image: elasticsearch:7.10.1
    platform: linux/amd64
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.10.1
    platform: linux/amd64
    ports:
      - "5601:5601"

  fastapi:
    build: .
    depends_on:
      - db
      - logstash
    ports:
      - "8000:8000"

volumes:
  postgres_data:
